added PyScript
freylint/masher pull request #2
Opened 2024-05-17 00:31 UTC by Sammojr614

Made the Python Script Lucas Requested

2024-05-17 00:45 UTC, freylint commented on flash.py
> +os.system("avrdude -c usbasp -p t84 -B 20 -U flash:w:target/avr-attiny84/release/semasher.elf")
I'd like it if you made the parameters to this function programmable.

Something like:
```python3
os.system(f"avrdude -c {PROGRAMMER} -p {TARGET} -B {TARGET_CLOCK_MHZ} -U flash:w:{BIN}")
```

2024-05-17 00:47 UTC, freylint commented on flash.py
> +os.system("avrdude -c usbasp -p t84 -B 20 -U flash:w:target/avr-attiny84/release/semasher.elf")
I'd also like the output of the programmer to show up in the console. This currently just returns a posix style success code.

2024-05-17 00:49 UTC, freylint requested changes
Good work. Just a couple more requirements that were failed to be mentioned.

2024-05-18 00:32 UTC, Sammojr614 commented
I Did the changes, Should be good now!

2024-05-18 01:36 UTC, freylint requested changes

2024-05-18 01:36 UTC, freylint commented on flash.py
> +PROGRAMMER = "sammo"
Little issue here. This is referring to the micro-controller programmer, as in the way we put code onto the chip. It should be `"usbasp"`. If you'd like to credit yourself please put your name in a comment in the top of the script.

2024-05-18 01:44 UTC, freylint approved these changes

2024-05-18 01:44 UTC, merged